const quotes = [
  { text: "Write hard and clear about what hurts.", author: "Ernest Hemingway" },
  { text: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L'Amour" },
  { text: "You can always edit a bad page. You can't edit a blank page.", author: "Jodi Picoult" },
  { text: "The first draft is just you telling yourself the story.", author: "Terry Pratchett" },
  { text: "If you want to be a writer, you must do two things above all others: read a lot and write a lot.", author: "Stephen King" },
  { text: "There is nothing to writing. All you do is sit down at a typewriter and bleed.", author: "Ernest Hemingway" },
  { text: "I write entirely to find out what I'm thinking.", author: "Joan Didion" },
  { text: "You don't start out writing good stuff. You start out writing crap and thinking it's good stuff, and then gradually you get better at it.", author: "Octavia E. Butler" },
  { text: "The scariest moment is always just before you start.", author: "Stephen King" },
  { text: "Almost all good writing begins with terrible first efforts.", author: "Anne Lamott" },
  { text: "A writer is someone for whom writing is more difficult than it is for other people.", author: "Thomas Mann" },
  { text: "Writing is thinking. To write well is to think clearly.", author: "David McCullough" },
  { text: "I can shake off everything as I write; my sorrows disappear, my courage is reborn.", author: "Anne Frank" },
  { text: "Fill your paper with the breathings of your heart.", author: "William Wordsworth" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "We write to taste life twice, in the moment and in retrospect.", author: "Anais Nin" },
  { text: "No tears in the writer, no tears in the reader.", author: "Robert Frost" },
  { text: "One day I will find the right words, and they will be simple.", author: "Jack Kerouac" },
  { text: "Writing is an exploration. You start from nothing and learn as you go.", author: "E.L. Doctorow" },
  { text: "The role of a writer is not to say what we can all say, but what we are unable to say.", author: "Anais Nin" },
  { text: "Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen.", author: "John Steinbeck" },
  { text: "I don't need an alarm clock. My ideas wake me.", author: "Ray Bradbury" },
  { text: "Substitute 'damn' every time you're inclined to write 'very'; your editor will delete it and the writing will be just as it should be.", author: "Mark Twain" },
  { text: "Read, read, read. Read everything.", author: "William Faulkner" },
  { text: "Tomorrow may be hell, but today was a good writing day, and on the good writing days nothing else matters.", author: "Neil Gaiman" },
  { text: "A word after a word after a word is power.", author: "Margaret Atwood" },
  { text: "I kept always two books in my pocket, one to read, one to write in.", author: "Robert Louis Stevenson" },
  { text: "You have to write the book that wants to be written.", author: "Madeleine L'Engle" },
  { text: "Close the door. Write with no one looking over your shoulder.", author: "Barbara Kingsolver" },
  { text: "Writing is like driving at night in the fog. You can only see as far as your headlights, but you can make the whole trip that way.", author: "E.L. Doctorow" },
  { text: "The desire to write grows with writing.", author: "Erasmus" },
  { text: "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.", author: "Scott Adams" },
  { text: "Don't tell me the moon is shining; show me the glint of light on broken glass.", author: "Anton Chekhov" },
  { text: "I love deadlines. I love the whooshing noise they make as they go by.", author: "Douglas Adams" },
  { text: "Writing is the painting of the voice.", author: "Voltaire" },
  { text: "To produce a mighty book, you must choose a mighty theme.", author: "Herman Melville" },
  { text: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", author: "Virginia Woolf" },
  { text: "I am irritated by my own writing. I am like a violinist whose ear is true, but whose fingers refuse to reproduce precisely the sound he hears within.", author: "Gustave Flaubert" },
  { text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", author: "Toni Morrison" },
  { text: "And by the way, everything in life is writable about if you have the outgoing guts to do it.", author: "Sylvia Plath" },
  { text: "Better to write for yourself and have no public, than to write for the public and have no self.", author: "Cyril Connolly" },
  { text: "When I sit down to write a book, I do not say to myself, 'I am going to produce a work of art.' I write it because there is some lie that I want to expose.", author: "George Orwell" },
  { text: "Not a wasted word. This has been a main point to my literary thinking all my life.", author: "Hunter S. Thompson" },
  { text: "Writing, to me, is simply thinking through my fingers.", author: "Isaac Asimov" },
  { text: "The most valuable of all talents is that of never using two words when one will do.", author: "Thomas Jefferson" },
  { text: "All you have to do is write one true sentence. Write the truest sentence that you know.", author: "Ernest Hemingway" },
  { text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "I do not over-intellectualize the production process. I try to keep it simple: Tell the damned story.", author: "Tom Clancy" },
  { text: "Quantity produces quality. If you only write a few things, you're doomed.", author: "Ray Bradbury" },
  { text: "The poet doesn't invent. He listens.", author: "Jean Cocteau" },
  { text: "If there's a voice in your head saying, 'You can't paint,' you must surely paint, and silence that voice.", author: "Vincent van Gogh" },
  { text: "Your first draft doesn't matter. Nobody's ever going to see your first draft. Nobody cares about your first draft.", author: "Neil Gaiman" },
  { text: "If you only write when you're inspired, you may be a fairly decent poet, but you're never going to be a novelist because you're going to have to make your word count each day and the words aren't going to wait for you to be inspired.", author: "Neil Gaiman" },
  { text: "If you plan on being read by more than one person, you can't possibly please everybody, so you might as well not bother.", author: "Diana Gabaldon" },
  { text: "Well, fine. Write your own book and leave out the heraldry. I don't care. This is my book, so I'm leaving in the heraldry.", author: "George R. R. Martin" },
  { text: "Write drunk, edit sober.", author: "Ernest Hemingway" },
  { text: "If I waited for perfection, I wouldn't write a thing.", author: "Margaret Atwood" },
  { text: "If your first scene doesn't give you a hard-on, throw it away!", author: "Samuel Fuller" },
  { text: "If you steal from one person, it's plagiarism. If you steal from a hundred, it's research. I do a lot of research.", author: "George R. R. Martin" },
  { text: "Every artist has thousands of bad drawings in them, and the only way to get rid of them is to draw them out.", author: "Chuck Jones" },
  { text: "The only writer to whom you should compare yourself is the writer you were yesterday.", author: "David Schlosser" },
  { text: "A professional writer is an amateur who didn't quit.", author: "Richard Bach" },
  { text: "If you're only going to write when you're inspired, you may be a fairly decent poet, but you will never be a novelist.", author: "Neil Gaiman" },
  { text: "How do I know what I think until I see what I say?", author: "E. M. Forster" },
  { text: "Fiction is the lie that tells the truth.", author: "Albert Camus" },
  { text: "Write. No amount of self-inflicted misery, altered states, black pullovers or being publicly obnoxious will ever add up to your being a writer. Writers write. On you go.", author: "A. L. Kennedy" },
  { text: "Mind your backups!", author: "Many writers who suffered hard-disk failure, 1985-2019" },
  { text: "Don't be the best at what you do. Be the only person who does what you do.", author: "Unknown" },
  { text: "I know writers who use subtext, and they're all cowards.", author: "Garth Marenghi" }
]

export function getRandomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)]
}

export default quotes
